alpha_vantage:
  api_key: "C3D3U6TR9CLD4C9P"
  base_url: "https://www.alphavantage.co/query"
newsapi:
  api_key: "160f1b012f8143aabc09cf2ea0511d3b"
  base_url: "https://newsapi.org/v2/everything"
model:
  pca_components: 2
  decay_rate: 0.1
  lookback_days: 30
  bayesian_prior_strength: 0.1
  nn_epochs: 10
  validation_split: 0.2
tickers:
  stock: "AAPL"
  market: "^IXIC"
  country: "^GSPC"
queries:
  stock: "Apple stock"
  country: "U.S. economy"
  market: "NASDAQ market"
visualization:
  smoothing_window: 3